package io.jamiekee.alphavantage.api.sector;

public enum Sector {

  TELECOMMUNICATION_SERVICES,
  CONSUMER_STAPLES,
  FINANCIALS,
  INDUSTRIALS,
  UTILITIES,
  HEALTH_CARE,
  REAL_ESTATE,
  MATERIALS,
  ENERGY,
  CONSUMER_DISCRETIONARY,
  INFORMATION_TECHNOLOGY;

}
